export type ApiDoc = {
  group: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "WS";
  path: string;
  access: string;
  summary: string;
  body?: string;
  success: string;
  failures: string;
  notes?: string;
  technical?: string;
};

const json = (value: unknown) => JSON.stringify(value, null, 2);

export const apiDocs: ApiDoc[] = [
  { group: "System", method: "GET", path: "/health", access: "Public", summary: "Check that the HTTP server is alive.", success: json({ status: "ok" }), failures: "200 only; this endpoint does not check MongoDB readiness.", technical: "This is a liveness check. It returns { status: \"ok\" } once Express is handling requests. It does not query MongoDB, Redis, the extraction worker, or the WebSocket server." },
  { group: "System", method: "GET", path: "/ready", access: "Public", summary: "Check whether the MongoDB connection is ready.", success: json({ status: "ready" }), failures: "503 { status: \"not_ready\" } when MongoDB is unavailable.", technical: "This is a readiness check backed by mongoose.connection.readyState. It returns 200 only when MongoDB is connected; otherwise it returns 503 so a deployment or load balancer can keep traffic away from an unready instance." },
  { group: "Authentication", method: "GET", path: "/api/auth/csrf", access: "Public", summary: "Issue a CSRF token for subsequent mutations.", success: json({ csrfToken: "token" }), failures: "500 if token creation fails.", notes: "The response also sets the csrf_token cookie." },
  { group: "Authentication", method: "POST", path: "/api/auth/register", access: "Public", summary: "Create a student account.", body: json({ firstName: "Ada", lastName: "Lovelace", email: "ada@example.com", password: "password123" }), success: json({ user: { _id: "665f2c9e8f1a2b3c4d5e6f70", firstName: "Ada", lastName: "Lovelace", email: "ada@example.com", role: "student", isVerified: false } }), failures: "400 validation error; 409 duplicate account; 429 rate limit." },
  { group: "Authentication", method: "POST", path: "/api/auth/verify-email", access: "Public", summary: "Verify an email address with its six-digit code.", body: json({ email: "ada@example.com", code: "123456" }), success: "200 verification result", failures: "400 validation or invalid code; 429 rate limit." },
  { group: "Authentication", method: "POST", path: "/api/auth/resend-verification", access: "Public", summary: "Send another email verification code.", body: json({ email: "ada@example.com" }), success: "200 resend result", failures: "400 validation; 404 account not found; 429 rate limit." },
  { group: "Authentication", method: "POST", path: "/api/auth/login", access: "Public", summary: "Authenticate a user and set access cookies.", body: json({ email: "ada@example.com", password: "password123" }), success: "200 authenticated user", failures: "400 validation; 401 invalid credentials; 429 rate limit.", technical: "On success, the server sets httpOnly access_token and refresh_token cookies. Browser clients must send credentials on later requests." },
  { group: "Authentication", method: "POST", path: "/api/auth/refresh", access: "Refresh cookie", summary: "Rotate the refresh session and issue a new access token.", success: "200 refreshed session", failures: "401 missing or invalid refresh session." },
  { group: "Authentication", method: "POST", path: "/api/auth/accept-invitation", access: "Public", summary: "Accept an admin invitation and create the invited account.", body: json({ token: "invitation-token", firstName: "Ada", lastName: "Lovelace", password: "password123", confirmPassword: "password123" }), success: "201 created invited user", failures: "400 validation or expired invitation; 409 invitation already used." },
  { group: "Authentication", method: "GET", path: "/api/auth/me", access: "Authenticated", summary: "Return the current authenticated user.", success: json({ user: { _id: "665f2c9e8f1a2b3c4d5e6f70", firstName: "Ada", lastName: "Lovelace", email: "ada@example.com", role: "student", isVerified: true } }), failures: "401 authentication required." },
  { group: "Authentication", method: "POST", path: "/api/auth/logout", access: "Authenticated", summary: "Revoke the current refresh session and clear cookies.", success: "200 logout result", failures: "401 when the session cannot be authenticated." },
  { group: "Authentication", method: "POST", path: "/api/auth/forgot-password", access: "Public", summary: "Request a password-reset code.", body: json({ email: "ada@example.com" }), success: "200 reset request result", failures: "400 validation; 429 rate limit." },
  { group: "Authentication", method: "POST", path: "/api/auth/reset-password", access: "Public", summary: "Set a new password using a reset code.", body: json({ email: "ada@example.com", code: "123456", password: "newpassword123" }), success: "200 password reset result", failures: "400 validation or invalid code; 429 rate limit." },
  { group: "Listings", method: "GET", path: "/api/listings", access: "Public", summary: "List available internship listings.", success: "200 listing collection", failures: "500 internal server error." },
  { group: "Listings", method: "GET", path: "/api/listings/:id", access: "Public", summary: "Get one internship listing.", success: "200 listing object", failures: "400 invalid ID; 404 listing not found." },
  { group: "Applications", method: "POST", path: "/api/applications", access: "Student", summary: "Apply to an internship listing.", body: json({ listingId: "64f000000000000000000000" }), success: json({ success: true, data: { _id: "665f2d1a8f1a2b3c4d5e6f71", studentId: "665f2c9e8f1a2b3c4d5e6f70", listingId: "64f000000000000000000000", companyId: "64f000000000000000000001", status: "applied", cvSnapshot: { url: "https://cdn.example.com/cv/ada-lovelace.pdf", filename: "ada-lovelace.pdf" }, appliedAt: "2026-09-25T10:30:00.000Z" } }), failures: "400 validation; 401 authentication; 403 role required; 404 listing not found; 409 application rule conflict." },
  { group: "Student", method: "GET", path: "/api/student/profile", access: "Student", summary: "Get the current student profile.", success: "200 profile object", failures: "401 authentication; 403 student role required." },
  { group: "Student", method: "PUT", path: "/api/student/profile", access: "Student + CSRF", summary: "Update the current student profile.", body: json({ institution: "Example University", skills: ["TypeScript", "MongoDB"], level: "400L" }), success: "200 updated profile", failures: "400 validation; 403 CSRF or role failure." },
  { group: "Student", method: "GET", path: "/api/student/dashboard", access: "Student", summary: "Get dashboard data for the current student.", success: "200 dashboard data", failures: "401 authentication; 403 student role required." },
  { group: "Student", method: "GET", path: "/api/student/applications", access: "Student", summary: "List the current student’s applications.", success: "200 application collection", failures: "401 authentication; 403 student role required." },
  { group: "Student", method: "GET", path: "/api/student/applications/:id", access: "Student", summary: "Get one application belonging to the student.", success: "200 application object", failures: "400 invalid ID; 404 application not found." },
  { group: "Student", method: "DELETE", path: "/api/student/applications/:id", access: "Student + CSRF", summary: "Withdraw an eligible application.", success: "200 withdrawal result", failures: "400 invalid ID; 403 CSRF or role failure; 404 not found; 409 withdrawal rule conflict." },
  { group: "Submissions", method: "POST", path: "/api/submissions", access: "Student/Admin + CSRF", summary: "Submit a listing URL or manual listing data for processing.", body: json({ type: "url", sourceUrl: "https://example.com/internship" }), success: "202 submission accepted; URL extraction continues asynchronously.", failures: "400 validation; 403 CSRF or role failure; 429 RATE_LIMITED or ACTIVE_JOB_LIMIT; 503 EXTRACTION_UNAVAILABLE.", technical: "URL submissions are normalized, rate-limited, deduplicated, persisted with a queued extraction job, and processed by the background worker. Use the Idempotency-Key header when retrying a request, especially when the raw URL exceeds 512 characters. Use the WebSocket /ws workflow to receive progress events. A manual submission is persisted immediately with status pending and returns 201." },
  { group: "Student", method: "POST", path: "/api/student/submissions", access: "Student + CSRF", summary: "Create a student listing submission.", body: json({ type: "manual", company: "Example Co", title: "Software Intern", description: "An internship opportunity" }), success: "201 submission created", failures: "400 validation; 403 CSRF or student role failure.", technical: "Use type manual when the listing fields are already known. For type url, sourceUrl is required and processing is asynchronous. The submission remains associated with the authenticated student." },
  { group: "Student", method: "GET", path: "/api/student/submissions", access: "Student", summary: "List the current student’s submissions.", success: "200 submission collection", failures: "401 authentication; 403 student role required." },
  { group: "Submissions", method: "WS", path: "/ws", access: "Authenticated cookie", summary: "Submit URL opportunities and receive extraction progress events over WebSocket.", body: json({ type: "submit_opportunity", requestId: "req-123", url: "https://example.com/internship", idempotencyKey: "opportunity-123" }), success: json({ type: "submission_accepted", requestId: "req-123", submissionId: "665f2e2a8f1a2b3c4d5e6f72", status: "pending" }), failures: "1008 Authentication required; error message for invalid JSON, unsupported message types, invalid URLs, rate limits, or unavailable extraction queue.", technical: "This is the real-time transport for URL submissions. Connect to ws(s)://<host>/ws with the access_token cookie. Send submit_opportunity, then subscribe_submission with the returned submissionId. The server sends submission_status, submission_completed, or submission_failed events. Connections are subject to heartbeat, idle, and maximum lifetime limits." },
  { group: "Notifications", method: "GET", path: "/api/notifications", access: "Authenticated", summary: "List notifications for the current user.", success: "200 notification collection", failures: "401 authentication required." },
  { group: "Notifications", method: "GET", path: "/api/notifications/unread-count", access: "Authenticated", summary: "Get the current unread notification count.", success: "200 unread count", failures: "401 authentication required." },
  { group: "Notifications", method: "PATCH", path: "/api/notifications/read-all", access: "Authenticated + CSRF", summary: "Mark all notifications as read.", success: "200 update result", failures: "401 authentication; 403 CSRF failure." },
  { group: "Notifications", method: "PATCH", path: "/api/notifications/:id/read", access: "Authenticated + CSRF", summary: "Mark one notification as read.", success: "200 update result", failures: "401 authentication; 403 CSRF failure; 404 not found." },
  { group: "Admin", method: "GET", path: "/api/admin/dashboard", access: "Admin/Super Admin", summary: "Get administrative dashboard data.", success: "200 dashboard data", failures: "401 authentication; 403 admin role required." },
  { group: "Admin", method: "GET", path: "/api/admin/users", access: "Admin/Super Admin", summary: "List users.", success: "200 user collection", failures: "401 authentication; 403 admin role required." },
  { group: "Admin", method: "GET", path: "/api/admin/users/:id", access: "Admin/Super Admin", summary: "Get one user.", success: "200 user object", failures: "400 invalid ID; 404 user not found." },
  { group: "Admin", method: "PATCH", path: "/api/admin/users/:id/suspend", access: "Admin/Super Admin + CSRF", summary: "Suspend a user account.", body: json({ reason: "Policy violation" }), success: "200 suspended user", failures: "400 validation; 403 CSRF or role failure; 404 user not found." },
  { group: "Admin", method: "PATCH", path: "/api/admin/users/:id/reactivate", access: "Admin/Super Admin + CSRF", summary: "Reactivate a user account.", success: "200 reactivated user", failures: "400 invalid ID; 403 CSRF or role failure; 404 user not found." },
  { group: "Admin", method: "PATCH", path: "/api/admin/users/:id/deactivate", access: "Admin/Super Admin + CSRF", summary: "Deactivate a user account.", success: "200 deactivated user", failures: "400 invalid ID; 403 CSRF or role failure; 404 user not found." },
  { group: "Admin", method: "GET", path: "/api/admin/students/:id/profile", access: "Admin/Super Admin", summary: "View a student profile.", success: "200 student profile", failures: "400 invalid ID; 404 student not found." },
  { group: "Admin", method: "POST", path: "/api/admin/students/:id/flag", access: "Admin/Super Admin + CSRF", summary: "Flag a student profile or CV issue.", body: json({ issue: "CV needs review", type: "cv" }), success: "201 flag created", failures: "400 validation; 403 CSRF or role failure; 404 student not found." },
  { group: "Admin", method: "GET", path: "/api/admin/companies", access: "Admin/Super Admin", summary: "List companies.", success: "200 company collection", failures: "401 authentication; 403 admin role required." },
  { group: "Admin", method: "POST", path: "/api/admin/companies", access: "Admin/Super Admin + CSRF", summary: "Create a company.", body: json({ name: "Example Co", website: "https://example.com" }), success: "201 company object", failures: "400 validation; 403 CSRF or role failure; 409 duplicate or similar company." },
  { group: "Admin", method: "GET", path: "/api/admin/companies/:id", access: "Admin/Super Admin", summary: "Get one company.", success: "200 company object", failures: "400 invalid ID; 404 company not found." },
  { group: "Admin", method: "PUT", path: "/api/admin/companies/:id", access: "Admin/Super Admin + CSRF", summary: "Update a company.", body: json({ name: "Updated Example Co" }), success: "200 company object", failures: "400 validation; 403 CSRF or role failure; 404 company not found." },
  { group: "Admin", method: "GET", path: "/api/admin/listings", access: "Admin/Super Admin", summary: "List all listings for administration.", success: "200 listing collection", failures: "401 authentication; 403 admin role required." },
  { group: "Admin", method: "POST", path: "/api/admin/listings", access: "Admin/Super Admin + CSRF", summary: "Create an internship listing.", body: json({ companyId: "64f000000000000000000000", title: "Software Intern", description: "An internship opportunity" }), success: "201 listing object", failures: "400 validation; 403 CSRF or role failure; 404 company not found." },
  { group: "Admin", method: "GET", path: "/api/admin/listings/:id", access: "Admin/Super Admin", summary: "Get one listing for administration.", success: "200 listing object", failures: "400 invalid ID; 404 listing not found." },
  { group: "Admin", method: "PUT", path: "/api/admin/listings/:id", access: "Admin/Super Admin + CSRF", summary: "Update an internship listing.", body: json({ title: "Updated Software Intern" }), success: "200 listing object", failures: "400 validation; 403 CSRF or role failure; 404 listing not found." },
  { group: "Admin", method: "PATCH", path: "/api/admin/listings/:id/close", access: "Admin/Super Admin + CSRF", summary: "Close an internship listing.", body: json({ reason: "Position filled" }), success: "200 closed listing", failures: "400 validation; 403 CSRF or role failure; 404 listing not found." },
  { group: "Admin", method: "PATCH", path: "/api/admin/listings/:id/expire", access: "Admin/Super Admin + CSRF", summary: "Expire an internship listing.", body: json({ reason: "Deadline passed" }), success: "200 expired listing", failures: "400 validation; 403 CSRF or role failure; 404 listing not found." },
  { group: "Admin", method: "GET", path: "/api/admin/submissions", access: "Admin/Super Admin", summary: "List submitted listings for review.", success: "200 submission collection", failures: "401 authentication; 403 admin role required." },
  { group: "Admin", method: "GET", path: "/api/admin/submissions/:id", access: "Admin/Super Admin", summary: "Get one listing submission.", success: "200 submission object", failures: "400 invalid ID; 404 submission not found." },
  { group: "Admin", method: "PATCH", path: "/api/admin/submissions/:id/approve", access: "Admin/Super Admin + CSRF", summary: "Approve a submission into a listing.", body: json({ companyId: "64f000000000000000000000", adminNote: "Reviewed" }), success: "200 approved submission/listing", failures: "400 validation; 403 CSRF or role failure; 404 submission/company not found; 409 state conflict." },
  { group: "Admin", method: "PATCH", path: "/api/admin/submissions/:id/reject", access: "Admin/Super Admin + CSRF", summary: "Reject a listing submission.", body: json({ adminNote: "Insufficient details" }), success: "200 rejected submission", failures: "400 validation; 403 CSRF or role failure; 404 submission not found; 409 state conflict." },
  { group: "Admin", method: "GET", path: "/api/admin/applications", access: "Admin/Super Admin", summary: "List applications for administration.", success: "200 application collection", failures: "401 authentication; 403 admin role required." },
  { group: "Admin", method: "GET", path: "/api/admin/applications/:id", access: "Admin/Super Admin", summary: "Get one application for administration.", success: "200 application object", failures: "400 invalid ID; 404 application not found." },
  { group: "Admin", method: "PATCH", path: "/api/admin/applications/:id/confirm-placement", access: "Admin/Super Admin + CSRF", summary: "Confirm an application placement.", body: json({ startDate: "2026-10-01T00:00:00.000Z", endDate: "2027-01-01T00:00:00.000Z", note: "Confirmed" }), success: "200 placement-confirmed application", failures: "400 validation or invalid dates; 403 CSRF or role failure; 404 application not found; 409 state conflict." },
  { group: "Admin", method: "PATCH", path: "/api/admin/applications/:id/review", access: "Admin/Super Admin + CSRF", summary: "Mark an application as reviewed.", body: json({ adminNote: "Under review" }), success: "200 reviewed application", failures: "400 validation; 403 CSRF or role failure; 404 application not found; 409 state conflict." },
  { group: "Admin", method: "PATCH", path: "/api/admin/applications/:id/accept", access: "Admin/Super Admin + CSRF", summary: "Accept an application.", body: json({ adminNote: "Accepted" }), success: "200 accepted application", failures: "400 validation; 403 CSRF or role failure; 404 application not found; 409 state conflict." },
  { group: "Admin", method: "PATCH", path: "/api/admin/applications/:id/reject", access: "Admin/Super Admin + CSRF", summary: "Reject an application.", body: json({ adminNote: "Not selected" }), success: "200 rejected application", failures: "400 validation; 403 CSRF or role failure; 404 application not found; 409 state conflict." },
  { group: "Admin", method: "GET", path: "/api/admin/audit-logs", access: "Admin/Super Admin", summary: "List audit log records.", success: "200 audit-log collection", failures: "401 authentication; 403 admin role required." },
  { group: "Invitations", method: "POST", path: "/api/admin/invitations", access: "Super Admin + CSRF", summary: "Invite an administrator.", body: json({ email: "admin@example.com" }), success: "201 invitation created", failures: "400 validation; 403 CSRF or super-admin role failure; 409 invitation conflict." },
  { group: "Invitations", method: "GET", path: "/api/admin/invitations", access: "Super Admin", summary: "List administrator invitations.", success: "200 invitation collection", failures: "401 authentication; 403 super-admin role required." },
  { group: "Invitations", method: "POST", path: "/api/admin/invitations/:id/resend", access: "Super Admin + CSRF", summary: "Resend an administrator invitation.", success: "200 invitation resent", failures: "400 invalid ID; 403 CSRF or role failure; 404 invitation not found." },
  { group: "Invitations", method: "DELETE", path: "/api/admin/invitations/:id", access: "Super Admin + CSRF", summary: "Revoke an administrator invitation.", success: "200 invitation revoked", failures: "400 invalid ID; 403 CSRF or role failure; 404 invitation not found." },
  { group: "Logs", method: "GET", path: "/api/logs", access: "Admin", summary: "List application logs.", success: "200 log collection", failures: "401 authentication; 403 admin role required." },
];
